export const EMAIL_VALIDATED = 'EMAIL_VALIDATED'
export const USERNAME_VALIDATED = 'USERNAME_VALIDATED'
export const PASSWORD_MATCH = 'PASSWORD_MATCH'
export const FULLNAME_VALIDATED = 'FULLNAME_VALIDATED'